from app.models.scenario import ScenarioDefinition


CLTV_TIMELOCK_SCENARIO = ScenarioDefinition.model_validate(
    {
        "scenario_id": "cltv-timelock",
        "version": "1.0.0",
        "name": "Real CLTV timelocked spend",
        "summary": (
            "Fund a native-SegWit OP_CHECKLOCKTIMEVERIFY policy, prove that its correctly signed spend is non-final "
            "before the target height, prove that final sequence and low nLockTime variants fail script validation, "
            "then advance regtest, broadcast the unchanged mature spend, and confirm it."
        ),
        "difficulty": "advanced",
        "related_lbcli_chapters": [6, 7, 10],
        "concepts": [
            "OP_CHECKLOCKTIMEVERIFY",
            "Absolute block-height lock",
            "nLockTime",
            "Input sequence",
            "P2WSH",
            "BIP143 signing",
        ],
        "required_capabilities": ["read_only", "wallet_read", "regtest_mutation"],
        "estimated_run_steps": 24,
        "steps": [
            {
                "step_id": "verify_chain",
                "type": "verify_runtime_chain",
                "phase": "setup",
                "title": "Verify the runtime chain",
                "description": "Require the configured node and live Bitcoin Core chain to agree on regtest.",
                "output_context_ref": "node.context",
            },
            {
                "step_id": "prepare_funding_wallet",
                "type": "prepare_isolated_wallet",
                "phase": "setup",
                "title": "Prepare the funding wallet",
                "description": "Use only the active wallet owned by this run's lab session.",
                "depends_on": ["verify_chain"],
                "wallet_role": "funder",
                "output_wallet_ref": "wallet.funder",
            },
            {
                "step_id": "prepare_cltv_signer",
                "type": "prepare_cltv_signer",
                "phase": "setup",
                "title": "Prepare an ephemeral policy signer",
                "description": "Create an in-memory secp256k1 signer that is never exported to Core, evidence, settings, or SQLite.",
                "depends_on": ["prepare_funding_wallet"],
                "signer_kind": "ephemeral_software_key",
                "output_signer_ref": "signer.ephemeral",
            },
            {
                "step_id": "generate_mining_address",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate a mining address",
                "description": "Generate a fresh funding-wallet address for maturity and confirmation blocks.",
                "depends_on": ["prepare_cltv_signer"],
                "wallet_ref": "wallet.funder",
                "label": "bitscope-cltv-mining",
                "address_type": "bech32",
                "output_address_ref": "address.mining",
            },
            {
                "step_id": "mine_mature_funds",
                "type": "mine_blocks",
                "phase": "setup",
                "title": "Mine mature funding",
                "description": "Mine 101 blocks in bounded batches so the funding wallet can spend.",
                "depends_on": ["generate_mining_address"],
                "address_ref": "address.mining",
                "blocks": 101,
                "output_blocks_ref": "blocks.maturity",
            },
            {
                "step_id": "create_cltv_policy",
                "type": "create_cltv_policy",
                "phase": "setup",
                "title": "Create the CLTV policy",
                "description": "Commit to a target four blocks beyond the current tip in a P2WSH witness script.",
                "depends_on": ["mine_mature_funds"],
                "signer_ref": "signer.ephemeral",
                "blocks_from_tip": 4,
                "output_policy_ref": "cltv.policy",
                "output_lock_height_ref": "cltv.lock_height",
            },
            {
                "step_id": "fund_cltv_policy",
                "type": "fund_cltv_policy",
                "phase": "setup",
                "title": "Fund the CLTV policy",
                "description": "Send 0.5 BTC to the policy with an explicit 2 sat/vB fee rate and retain its exact outpoint.",
                "depends_on": ["create_cltv_policy"],
                "wallet_ref": "wallet.funder",
                "policy_ref": "cltv.policy",
                "amount_btc": "0.50000000",
                "fee_rate_sat_vb": "2.000",
                "output_funding_ref": "cltv.funding",
            },
            {
                "step_id": "confirm_cltv_funding",
                "type": "mine_confirmation_blocks",
                "phase": "setup",
                "title": "Confirm the policy output",
                "description": "Mine one block so the CLTV outpoint is confirmed while the target remains in the future.",
                "depends_on": ["fund_cltv_policy"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.funding_confirmation",
            },
            {
                "step_id": "generate_destination",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate the spend destination",
                "description": "Generate a fresh funding-wallet destination for the policy spend.",
                "depends_on": ["confirm_cltv_funding"],
                "wallet_ref": "wallet.funder",
                "label": "bitscope-cltv-destination",
                "address_type": "bech32",
                "output_address_ref": "address.destination",
            },
            {
                "step_id": "construct_premature_spend",
                "type": "create_cltv_spend",
                "phase": "execution",
                "title": "Construct the valid CLTV spend",
                "description": "Sign a one-input spend with nLockTime equal to the policy target and a non-final sequence.",
                "depends_on": ["generate_destination"],
                "signer_ref": "signer.ephemeral",
                "policy_ref": "cltv.policy",
                "funding_ref": "cltv.funding",
                "recipient_address_ref": "address.destination",
                "lock_height_adjustment": 0,
                "sequence": 4294967294,
                "fee_sats": 10000,
                "output_transaction_ref": "spend.valid",
            },
            {
                "step_id": "reject_premature_spend",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Prove the spend is premature",
                "description": "Require Core to reject the correctly signed transaction as non-final before the target height.",
                "depends_on": ["construct_premature_spend"],
                "transaction_ref": "spend.valid",
                "output_acceptance_ref": "acceptance.premature",
            },
            {
                "step_id": "construct_final_sequence_spend",
                "type": "create_cltv_spend",
                "phase": "attack",
                "title": "Construct a final-sequence variant",
                "description": "Sign the same policy spend with sequence 0xffffffff, which disables transaction locktime semantics.",
                "depends_on": ["reject_premature_spend"],
                "signer_ref": "signer.ephemeral",
                "policy_ref": "cltv.policy",
                "funding_ref": "cltv.funding",
                "recipient_address_ref": "address.destination",
                "lock_height_adjustment": 0,
                "sequence": 4294967295,
                "fee_sats": 10000,
                "output_transaction_ref": "spend.final_sequence",
            },
            {
                "step_id": "reject_final_sequence_spend",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Prove sequence is enforced",
                "description": "Require CLTV script validation to reject the final-sequence variant.",
                "depends_on": ["construct_final_sequence_spend"],
                "transaction_ref": "spend.final_sequence",
                "output_acceptance_ref": "acceptance.final_sequence",
            },
            {
                "step_id": "advance_to_maturity",
                "type": "advance_absolute_timelock",
                "phase": "attack",
                "title": "Advance to the target height",
                "description": "Mine only the bounded number of blocks required to reach the policy height.",
                "depends_on": ["reject_final_sequence_spend"],
                "address_ref": "address.mining",
                "target_height_ref": "cltv.lock_height",
                "output_height_ref": "cltv.mature_height",
            },
            {
                "step_id": "construct_low_locktime_spend",
                "type": "create_cltv_spend",
                "phase": "attack",
                "title": "Construct a low-locktime variant",
                "description": "Sign a variant whose nLockTime is one block below the script requirement.",
                "depends_on": ["advance_to_maturity"],
                "signer_ref": "signer.ephemeral",
                "policy_ref": "cltv.policy",
                "funding_ref": "cltv.funding",
                "recipient_address_ref": "address.destination",
                "lock_height_adjustment": -1,
                "sequence": 4294967294,
                "fee_sats": 10000,
                "output_transaction_ref": "spend.low_locktime",
            },
            {
                "step_id": "reject_low_locktime_spend",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Prove nLockTime is enforced",
                "description": "Require CLTV script validation to reject the low-locktime variant even after chain maturity.",
                "depends_on": ["construct_low_locktime_spend"],
                "transaction_ref": "spend.low_locktime",
                "output_acceptance_ref": "acceptance.low_locktime",
            },
            {
                "step_id": "accept_mature_spend",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Preflight the mature spend",
                "description": "Require Core to accept the unchanged transaction that was non-final before maturity.",
                "depends_on": ["reject_low_locktime_spend"],
                "transaction_ref": "spend.valid",
                "output_acceptance_ref": "acceptance.mature",
            },
            {
                "step_id": "broadcast_mature_spend",
                "type": "broadcast_transaction",
                "phase": "attack",
                "title": "Broadcast the mature spend",
                "description": "Broadcast only the preflighted mature transaction.",
                "depends_on": ["accept_mature_spend"],
                "transaction_ref": "spend.valid",
                "output_txid_ref": "spend.txid",
            },
            {
                "step_id": "inspect_spend_mempool",
                "type": "query_mempool_entry",
                "phase": "attack",
                "title": "Inspect the spend in mempool",
                "description": "Record the accepted CLTV spend's mempool entry.",
                "depends_on": ["broadcast_mature_spend"],
                "txid_ref": "spend.txid",
                "output_mempool_ref": "spend.mempool",
            },
            {
                "step_id": "confirm_mature_spend",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm the mature spend",
                "description": "Mine one block containing the mature CLTV spend.",
                "depends_on": ["inspect_spend_mempool"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.spend_confirmation",
            },
            {
                "step_id": "decode_confirmed_spend",
                "type": "decode_transaction",
                "phase": "attack",
                "title": "Decode the confirmed spend",
                "description": "Read and decode the confirmed transaction, preserving its locktime and witness commitment.",
                "depends_on": ["confirm_mature_spend"],
                "transaction_ref": "spend.valid",
                "output_decoded_ref": "spend.confirmed",
            },
            {
                "step_id": "verify_results",
                "type": "evaluate_assertions",
                "phase": "verification",
                "title": "Evaluate CLTV assertions",
                "description": "Evaluate premature rejection, script constraints, maturity, acceptance, and confirmation.",
                "depends_on": ["decode_confirmed_spend"],
                "assertion_ids": [
                    "premature_rejected",
                    "timelock_immature",
                    "final_sequence_rejected",
                    "low_locktime_rejected",
                    "timelock_mature",
                    "mature_spend_accepted",
                    "spend_confirmed",
                ],
            },
            {
                "step_id": "export_proof",
                "type": "export_evidence",
                "phase": "export",
                "title": "Export the proof bundle",
                "description": "Expose the policy, signed variants, Core outcomes, assertions, commands, manifest, and ZIP export.",
                "depends_on": ["verify_results"],
                "output_bundle_ref": "proof.bundle",
            },
            {
                "step_id": "cleanup",
                "type": "cleanup_lab",
                "phase": "cleanup",
                "title": "Clean up signer and wallet state",
                "description": "Drop the ephemeral signer reference and unload only the wallet owned by this lab session.",
                "depends_on": ["export_proof"],
            },
        ],
        "assertions": [
            {
                "assertion_id": "premature_rejected",
                "kind": "rpc_failed_with_category",
                "after_step_id": "reject_premature_spend",
                "subject_ref": "acceptance.premature",
                "expected_category": "mempool_policy",
                "description": "Core reports the valid signed transaction as non-final before its target height.",
            },
            {
                "assertion_id": "timelock_immature",
                "kind": "timelock_immature",
                "after_step_id": "reject_premature_spend",
                "subject_ref": "acceptance.premature",
                "description": "The current height is below the CLTV target when the valid spend is first tested.",
            },
            {
                "assertion_id": "final_sequence_rejected",
                "kind": "rpc_failed_with_category",
                "after_step_id": "reject_final_sequence_spend",
                "subject_ref": "acceptance.final_sequence",
                "expected_category": "script_verification",
                "description": "CLTV rejects sequence 0xffffffff because locktime is disabled for that input.",
            },
            {
                "assertion_id": "low_locktime_rejected",
                "kind": "rpc_failed_with_category",
                "after_step_id": "reject_low_locktime_spend",
                "subject_ref": "acceptance.low_locktime",
                "expected_category": "script_verification",
                "description": "CLTV rejects transaction nLockTime below the value committed in the witness script.",
            },
            {
                "assertion_id": "timelock_mature",
                "kind": "timelock_mature",
                "after_step_id": "advance_to_maturity",
                "subject_ref": "cltv.mature_height",
                "description": "The regtest tip reaches the absolute policy height before the valid spend is accepted.",
            },
            {
                "assertion_id": "mature_spend_accepted",
                "kind": "mempool_policy_accepted",
                "after_step_id": "accept_mature_spend",
                "subject_ref": "acceptance.mature",
                "description": "Core accepts the unchanged valid transaction once the chain reaches maturity.",
            },
            {
                "assertion_id": "spend_confirmed",
                "kind": "transaction_confirmed",
                "after_step_id": "decode_confirmed_spend",
                "subject_ref": "spend.confirmed",
                "description": "The mature CLTV spend confirms with a matching decoded txid and committed nLockTime.",
            },
        ],
    }
)
