from app.models.scenario import ScenarioDefinition


COMMUNITY_TREASURY_SCENARIO = ScenarioDefinition.model_validate(
    {
        "scenario_id": "community-treasury-recovery",
        "version": "1.0.0",
        "name": "Community Treasury Recovery",
        "summary": (
            "Create a public three-path P2WSH Miniscript treasury across isolated signer wallets, prove immediate "
            "2-of-3 spending, reject insufficient and premature recovery attempts for their exact reasons, then "
            "mature and confirm both the recovery and longer-delay emergency branches."
        ),
        "difficulty": "advanced",
        "related_lbcli_chapters": [6, 7, 10],
        "concepts": [
            "P2WSH Miniscript",
            "2-of-3 threshold",
            "PSBT",
            "BIP68 relative timelock",
            "Community treasury",
            "Recovery policy",
            "Independent signer contexts",
        ],
        "required_capabilities": ["read_only", "wallet_read", "regtest_mutation"],
        "estimated_run_steps": 54,
        "steps": [
            {
                "step_id": "verify_chain",
                "type": "verify_runtime_chain",
                "phase": "setup",
                "title": "Verify the runtime chain",
                "description": "Require the configured node and live Bitcoin Core chain to agree on regtest.",
                "output_context_ref": "node.context",
            },
            {
                "step_id": "prepare_funding_wallet",
                "type": "prepare_isolated_wallet",
                "phase": "setup",
                "title": "Prepare the funding wallet",
                "description": "Use only the active funding wallet owned by this run's lab session.",
                "depends_on": ["verify_chain"],
                "wallet_role": "funder",
                "output_wallet_ref": "wallet.funder",
            },
            {
                "step_id": "prepare_participants",
                "type": "prepare_treasury_participants",
                "phase": "setup",
                "title": "Prepare treasury participants",
                "description": "Create nine signer wallets and one private-keys-disabled coordinator within the session namespace.",
                "depends_on": ["prepare_funding_wallet"],
                "signers_per_group": 3,
                "required_signatures": 2,
                "output_participants_ref": "participants.treasury",
                "output_coordinator_wallet_ref": "wallet.coordinator",
            },
            {
                "step_id": "generate_mining_address",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate a mining address",
                "description": "Generate a fresh funding-wallet address for bounded maturity and confirmation mining.",
                "depends_on": ["prepare_participants"],
                "wallet_ref": "wallet.funder",
                "label": "bitscope-treasury-mining",
                "address_type": "bech32",
                "output_address_ref": "address.mining",
            },
            {
                "step_id": "mine_mature_funds",
                "type": "mine_blocks",
                "phase": "setup",
                "title": "Mine mature funding",
                "description": "Mine 101 blocks in bounded batches so the session wallet can fund all policy branches.",
                "depends_on": ["generate_mining_address"],
                "address_ref": "address.mining",
                "blocks": 101,
                "output_blocks_ref": "blocks.maturity",
            },
            {
                "step_id": "materialize_policy",
                "type": "materialize_treasury_policy",
                "phase": "setup",
                "title": "Materialize the treasury policy",
                "description": "Normalize, derive, and import the public three-path descriptor into the non-signing coordinator.",
                "depends_on": ["mine_mature_funds"],
                "participants_ref": "participants.treasury",
                "coordinator_wallet_ref": "wallet.coordinator",
                "recovery_delay_blocks": 5,
                "emergency_delay_blocks": 10,
                "output_policy_ref": "treasury.policy",
                "output_address_ref": "treasury.address",
                "output_decision_tree_ref": "treasury.decision_tree",
            },
            {
                "step_id": "generate_destination",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate the spend destination",
                "description": "Generate one fresh funding-wallet destination for the three independent branch proofs.",
                "depends_on": ["materialize_policy"],
                "wallet_ref": "wallet.funder",
                "label": "bitscope-treasury-destination",
                "address_type": "bech32",
                "output_address_ref": "address.destination",
            },
            {
                "step_id": "fund_immediate",
                "type": "fund_treasury_policy",
                "phase": "execution",
                "title": "Fund the immediate branch proof",
                "description": "Create a fresh 1 BTC policy output with an explicit 2 sat/vB funding fee rate.",
                "depends_on": ["generate_destination"],
                "wallet_ref": "wallet.funder",
                "policy_ref": "treasury.policy",
                "branch": "immediate",
                "amount_btc": "1.00000000",
                "fee_rate_sat_vb": "2.000",
                "output_funding_ref": "funding.immediate",
            },
            {
                "step_id": "confirm_immediate_funding",
                "type": "mine_confirmation_blocks",
                "phase": "execution",
                "title": "Confirm immediate funding",
                "description": "Mine one block confirming the exact immediate-path policy outpoint.",
                "depends_on": ["fund_immediate"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.immediate_funding",
            },
            {
                "step_id": "create_immediate_psbt",
                "type": "create_treasury_spend_psbt",
                "phase": "execution",
                "title": "Create the immediate spend PSBT",
                "description": "Construct and enrich a version-2 PSBT spending the confirmed policy output.",
                "depends_on": ["confirm_immediate_funding"],
                "coordinator_wallet_ref": "wallet.coordinator",
                "funding_ref": "funding.immediate",
                "recipient_address_ref": "address.destination",
                "branch": "immediate",
                "sequence": 4294967294,
                "fee_sats": 10000,
                "output_psbt_ref": "psbt.immediate.unsigned",
            },
            {
                "step_id": "sign_immediate_one",
                "type": "sign_treasury_psbt",
                "phase": "execution",
                "title": "Add one operator signature",
                "description": "Process the PSBT with only the first treasury operator.",
                "depends_on": ["create_immediate_psbt"],
                "participants_ref": "participants.treasury",
                "psbt_ref": "psbt.immediate.unsigned",
                "signer_role": "operator",
                "signer_positions": [1],
                "output_psbt_ref": "psbt.immediate.partial",
                "output_signature_count_ref": "signatures.immediate.partial",
            },
            {
                "step_id": "finalize_immediate_incomplete",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Prove one operator is insufficient",
                "description": "Require one operator signature to remain incomplete and unextractable.",
                "depends_on": ["sign_immediate_one"],
                "psbt_ref": "psbt.immediate.partial",
                "extract": False,
                "output_psbt_ref": "psbt.immediate.incomplete",
            },
            {
                "step_id": "sign_immediate_two",
                "type": "sign_treasury_psbt",
                "phase": "attack",
                "title": "Reach the operator threshold",
                "description": "Add the second independent operator signature without finalizing early.",
                "depends_on": ["finalize_immediate_incomplete"],
                "participants_ref": "participants.treasury",
                "psbt_ref": "psbt.immediate.partial",
                "signer_role": "operator",
                "signer_positions": [2],
                "output_psbt_ref": "psbt.immediate.threshold",
                "output_signature_count_ref": "signatures.immediate.threshold",
            },
            {
                "step_id": "finalize_immediate",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Finalize the immediate spend",
                "description": "Extract the threshold-complete immediate transaction.",
                "depends_on": ["sign_immediate_two"],
                "psbt_ref": "psbt.immediate.threshold",
                "extract": True,
                "output_transaction_ref": "transaction.immediate",
            },
            {
                "step_id": "preflight_immediate",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Preflight the immediate spend",
                "description": "Require Core to accept the finalized immediate-path transaction.",
                "depends_on": ["finalize_immediate"],
                "transaction_ref": "transaction.immediate",
                "output_acceptance_ref": "acceptance.immediate",
            },
            {
                "step_id": "broadcast_immediate",
                "type": "broadcast_transaction",
                "phase": "attack",
                "title": "Broadcast the immediate spend",
                "description": "Broadcast only the preflighted immediate transaction.",
                "depends_on": ["preflight_immediate"],
                "transaction_ref": "transaction.immediate",
                "output_txid_ref": "txid.immediate",
            },
            {
                "step_id": "inspect_immediate_mempool",
                "type": "query_mempool_entry",
                "phase": "attack",
                "title": "Inspect the immediate spend",
                "description": "Record the immediate transaction's live mempool entry.",
                "depends_on": ["broadcast_immediate"],
                "txid_ref": "txid.immediate",
                "output_mempool_ref": "mempool.immediate",
            },
            {
                "step_id": "confirm_immediate",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm the immediate spend",
                "description": "Mine one block containing the immediate spend.",
                "depends_on": ["inspect_immediate_mempool"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.immediate_confirmation",
            },
            {
                "step_id": "decode_immediate",
                "type": "decode_transaction",
                "phase": "attack",
                "title": "Decode the confirmed immediate spend",
                "description": "Verify the confirmed transaction has the broadcast txid.",
                "depends_on": ["confirm_immediate"],
                "transaction_ref": "transaction.immediate",
                "output_decoded_ref": "transaction.immediate.confirmed",
            },
            {
                "step_id": "fund_recovery",
                "type": "fund_treasury_policy",
                "phase": "attack",
                "title": "Fund the recovery proof",
                "description": "Create a second independently confirmed policy output for relative recovery.",
                "depends_on": ["decode_immediate"],
                "wallet_ref": "wallet.funder",
                "policy_ref": "treasury.policy",
                "branch": "recovery",
                "amount_btc": "1.00000000",
                "fee_rate_sat_vb": "2.000",
                "output_funding_ref": "funding.recovery",
            },
            {
                "step_id": "confirm_recovery_funding",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm recovery funding",
                "description": "Mine one block establishing the recovery output's BIP68 age anchor.",
                "depends_on": ["fund_recovery"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.recovery_funding",
            },
            {
                "step_id": "create_recovery_psbt",
                "type": "create_treasury_spend_psbt",
                "phase": "attack",
                "title": "Create the recovery PSBT",
                "description": "Set input sequence to the configured five-block recovery delay.",
                "depends_on": ["confirm_recovery_funding"],
                "coordinator_wallet_ref": "wallet.coordinator",
                "funding_ref": "funding.recovery",
                "recipient_address_ref": "address.destination",
                "branch": "recovery",
                "sequence": 5,
                "fee_sats": 10000,
                "output_psbt_ref": "psbt.recovery.unsigned",
            },
            {
                "step_id": "sign_recovery_one",
                "type": "sign_treasury_psbt",
                "phase": "attack",
                "title": "Add one recovery signature",
                "description": "Process the recovery PSBT with only the first recovery signer.",
                "depends_on": ["create_recovery_psbt"],
                "participants_ref": "participants.treasury",
                "psbt_ref": "psbt.recovery.unsigned",
                "signer_role": "recovery",
                "signer_positions": [1],
                "output_psbt_ref": "psbt.recovery.partial",
                "output_signature_count_ref": "signatures.recovery.partial",
            },
            {
                "step_id": "finalize_recovery_incomplete",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Prove one recovery signer is insufficient",
                "description": "Require the one-signature recovery PSBT to remain incomplete.",
                "depends_on": ["sign_recovery_one"],
                "psbt_ref": "psbt.recovery.partial",
                "extract": False,
                "output_psbt_ref": "psbt.recovery.incomplete",
            },
            {
                "step_id": "sign_recovery_two",
                "type": "sign_treasury_psbt",
                "phase": "attack",
                "title": "Reach the recovery threshold",
                "description": "Add the second recovery signature without finalizing early.",
                "depends_on": ["finalize_recovery_incomplete"],
                "participants_ref": "participants.treasury",
                "psbt_ref": "psbt.recovery.partial",
                "signer_role": "recovery",
                "signer_positions": [2],
                "output_psbt_ref": "psbt.recovery.threshold",
                "output_signature_count_ref": "signatures.recovery.threshold",
            },
            {
                "step_id": "finalize_recovery",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Finalize the recovery spend",
                "description": "Extract the threshold-complete recovery transaction before it is mature.",
                "depends_on": ["sign_recovery_two"],
                "psbt_ref": "psbt.recovery.threshold",
                "extract": True,
                "output_transaction_ref": "transaction.recovery",
            },
            {
                "step_id": "reject_premature_recovery",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Reject premature recovery",
                "description": "Require the exact non-BIP68-final rejection before five relative blocks.",
                "depends_on": ["finalize_recovery"],
                "transaction_ref": "transaction.recovery",
                "output_acceptance_ref": "acceptance.recovery.premature",
            },
            {
                "step_id": "create_wrong_sequence_psbt",
                "type": "create_treasury_spend_psbt",
                "phase": "attack",
                "title": "Create an incorrect-sequence recovery PSBT",
                "description": "Set sequence to four, which cannot satisfy the five-block Miniscript branch.",
                "depends_on": ["reject_premature_recovery"],
                "coordinator_wallet_ref": "wallet.coordinator",
                "funding_ref": "funding.recovery",
                "recipient_address_ref": "address.destination",
                "branch": "recovery",
                "sequence": 4,
                "fee_sats": 10000,
                "output_psbt_ref": "psbt.recovery.wrong_sequence",
            },
            {
                "step_id": "sign_wrong_sequence_psbt",
                "type": "sign_treasury_psbt",
                "phase": "attack",
                "title": "Sign the incorrect-sequence PSBT",
                "description": "Collect both recovery signatures so sequence remains the only unsatisfied policy condition.",
                "depends_on": ["create_wrong_sequence_psbt"],
                "participants_ref": "participants.treasury",
                "psbt_ref": "psbt.recovery.wrong_sequence",
                "signer_role": "recovery",
                "signer_positions": [1, 2],
                "output_psbt_ref": "psbt.recovery.wrong_sequence.signed",
                "output_signature_count_ref": "signatures.recovery.wrong_sequence",
            },
            {
                "step_id": "finalize_wrong_sequence_incomplete",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Prove incorrect sequence is incomplete",
                "description": "Require Core's Miniscript finalizer to return complete=false and no transaction hex.",
                "depends_on": ["sign_wrong_sequence_psbt"],
                "psbt_ref": "psbt.recovery.wrong_sequence.signed",
                "extract": False,
                "output_psbt_ref": "psbt.recovery.wrong_sequence.incomplete",
            },
            {
                "step_id": "advance_recovery_delay",
                "type": "advance_relative_timelock",
                "phase": "attack",
                "title": "Advance the recovery delay",
                "description": "Mine exactly five blocks to mature the unchanged recovery transaction.",
                "depends_on": ["finalize_wrong_sequence_incomplete"],
                "address_ref": "address.mining",
                "blocks": 5,
                "output_height_ref": "height.recovery.mature",
            },
            {
                "step_id": "preflight_mature_recovery",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Preflight mature recovery",
                "description": "Require Core to accept the unchanged recovery transaction after maturity.",
                "depends_on": ["advance_recovery_delay"],
                "transaction_ref": "transaction.recovery",
                "output_acceptance_ref": "acceptance.recovery.mature",
            },
            {
                "step_id": "broadcast_recovery",
                "type": "broadcast_transaction",
                "phase": "attack",
                "title": "Broadcast mature recovery",
                "description": "Broadcast the preflighted unchanged recovery transaction.",
                "depends_on": ["preflight_mature_recovery"],
                "transaction_ref": "transaction.recovery",
                "output_txid_ref": "txid.recovery",
            },
            {
                "step_id": "inspect_recovery_mempool",
                "type": "query_mempool_entry",
                "phase": "attack",
                "title": "Inspect the recovery spend",
                "description": "Record the recovery transaction's mempool entry.",
                "depends_on": ["broadcast_recovery"],
                "txid_ref": "txid.recovery",
                "output_mempool_ref": "mempool.recovery",
            },
            {
                "step_id": "confirm_recovery",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm recovery",
                "description": "Mine one block containing the mature recovery transaction.",
                "depends_on": ["inspect_recovery_mempool"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.recovery_confirmation",
            },
            {
                "step_id": "decode_recovery",
                "type": "decode_transaction",
                "phase": "attack",
                "title": "Decode confirmed recovery",
                "description": "Verify the confirmed recovery transaction has the broadcast txid.",
                "depends_on": ["confirm_recovery"],
                "transaction_ref": "transaction.recovery",
                "output_decoded_ref": "transaction.recovery.confirmed",
            },
            {
                "step_id": "fund_emergency",
                "type": "fund_treasury_policy",
                "phase": "attack",
                "title": "Fund the emergency proof",
                "description": "Create a third independently confirmed output for the longer-delay emergency branch.",
                "depends_on": ["decode_recovery"],
                "wallet_ref": "wallet.funder",
                "policy_ref": "treasury.policy",
                "branch": "emergency",
                "amount_btc": "1.00000000",
                "fee_rate_sat_vb": "2.000",
                "output_funding_ref": "funding.emergency",
            },
            {
                "step_id": "confirm_emergency_funding",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm emergency funding",
                "description": "Mine one block establishing the emergency output's relative age anchor.",
                "depends_on": ["fund_emergency"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.emergency_funding",
            },
            {
                "step_id": "create_emergency_psbt",
                "type": "create_treasury_spend_psbt",
                "phase": "attack",
                "title": "Create the emergency PSBT",
                "description": "Set input sequence to the configured ten-block emergency delay.",
                "depends_on": ["confirm_emergency_funding"],
                "coordinator_wallet_ref": "wallet.coordinator",
                "funding_ref": "funding.emergency",
                "recipient_address_ref": "address.destination",
                "branch": "emergency",
                "sequence": 10,
                "fee_sats": 10000,
                "output_psbt_ref": "psbt.emergency.unsigned",
            },
            {
                "step_id": "sign_emergency_one",
                "type": "sign_treasury_psbt",
                "phase": "attack",
                "title": "Add one emergency signature",
                "description": "Process the emergency PSBT with only the first emergency signer.",
                "depends_on": ["create_emergency_psbt"],
                "participants_ref": "participants.treasury",
                "psbt_ref": "psbt.emergency.unsigned",
                "signer_role": "emergency",
                "signer_positions": [1],
                "output_psbt_ref": "psbt.emergency.partial",
                "output_signature_count_ref": "signatures.emergency.partial",
            },
            {
                "step_id": "finalize_emergency_incomplete",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Prove one emergency signer is insufficient",
                "description": "Require the one-signature emergency PSBT to remain incomplete.",
                "depends_on": ["sign_emergency_one"],
                "psbt_ref": "psbt.emergency.partial",
                "extract": False,
                "output_psbt_ref": "psbt.emergency.incomplete",
            },
            {
                "step_id": "sign_emergency_two",
                "type": "sign_treasury_psbt",
                "phase": "attack",
                "title": "Reach the emergency threshold",
                "description": "Add the second emergency signature without finalizing early.",
                "depends_on": ["finalize_emergency_incomplete"],
                "participants_ref": "participants.treasury",
                "psbt_ref": "psbt.emergency.partial",
                "signer_role": "emergency",
                "signer_positions": [2],
                "output_psbt_ref": "psbt.emergency.threshold",
                "output_signature_count_ref": "signatures.emergency.threshold",
            },
            {
                "step_id": "finalize_emergency",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Finalize the emergency spend",
                "description": "Extract the threshold-complete emergency transaction before maturity.",
                "depends_on": ["sign_emergency_two"],
                "psbt_ref": "psbt.emergency.threshold",
                "extract": True,
                "output_transaction_ref": "transaction.emergency",
            },
            {
                "step_id": "reject_premature_emergency",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Reject premature emergency recovery",
                "description": "Require the exact non-BIP68-final rejection before ten relative blocks.",
                "depends_on": ["finalize_emergency"],
                "transaction_ref": "transaction.emergency",
                "output_acceptance_ref": "acceptance.emergency.premature",
            },
            {
                "step_id": "advance_emergency_delay",
                "type": "advance_relative_timelock",
                "phase": "attack",
                "title": "Advance the emergency delay",
                "description": "Mine exactly ten blocks to mature the unchanged emergency transaction.",
                "depends_on": ["reject_premature_emergency"],
                "address_ref": "address.mining",
                "blocks": 10,
                "output_height_ref": "height.emergency.mature",
            },
            {
                "step_id": "preflight_mature_emergency",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Preflight mature emergency recovery",
                "description": "Require Core to accept the unchanged emergency transaction after maturity.",
                "depends_on": ["advance_emergency_delay"],
                "transaction_ref": "transaction.emergency",
                "output_acceptance_ref": "acceptance.emergency.mature",
            },
            {
                "step_id": "broadcast_emergency",
                "type": "broadcast_transaction",
                "phase": "attack",
                "title": "Broadcast mature emergency recovery",
                "description": "Broadcast the preflighted unchanged emergency transaction.",
                "depends_on": ["preflight_mature_emergency"],
                "transaction_ref": "transaction.emergency",
                "output_txid_ref": "txid.emergency",
            },
            {
                "step_id": "inspect_emergency_mempool",
                "type": "query_mempool_entry",
                "phase": "attack",
                "title": "Inspect the emergency spend",
                "description": "Record the emergency transaction's mempool entry.",
                "depends_on": ["broadcast_emergency"],
                "txid_ref": "txid.emergency",
                "output_mempool_ref": "mempool.emergency",
            },
            {
                "step_id": "confirm_emergency",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm emergency recovery",
                "description": "Mine one block containing the mature emergency transaction.",
                "depends_on": ["inspect_emergency_mempool"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.emergency_confirmation",
            },
            {
                "step_id": "decode_emergency",
                "type": "decode_transaction",
                "phase": "attack",
                "title": "Decode confirmed emergency recovery",
                "description": "Verify the confirmed emergency transaction has the broadcast txid.",
                "depends_on": ["confirm_emergency"],
                "transaction_ref": "transaction.emergency",
                "output_decoded_ref": "transaction.emergency.confirmed",
            },
            {
                "step_id": "verify_results",
                "type": "evaluate_assertions",
                "phase": "verification",
                "title": "Evaluate treasury assertions",
                "description": "Evaluate threshold, exact rejection, maturity, acceptance, and confirmation evidence for all paths.",
                "depends_on": ["decode_emergency"],
                "assertion_ids": [
                    "immediate_insufficient",
                    "immediate_psbt_incomplete",
                    "immediate_threshold_not_met",
                    "immediate_threshold_met",
                    "immediate_accepted",
                    "immediate_confirmed",
                    "recovery_insufficient",
                    "recovery_psbt_incomplete",
                    "recovery_threshold_not_met",
                    "recovery_threshold_met",
                    "premature_recovery_rejected",
                    "recovery_timelock_immature",
                    "wrong_sequence_incomplete",
                    "recovery_timelock_mature",
                    "recovery_accepted",
                    "recovery_confirmed",
                    "emergency_insufficient",
                    "emergency_psbt_incomplete",
                    "emergency_threshold_not_met",
                    "emergency_threshold_met",
                    "premature_emergency_rejected",
                    "emergency_timelock_immature",
                    "emergency_timelock_mature",
                    "emergency_accepted",
                    "emergency_confirmed",
                ],
            },
            {
                "step_id": "export_proof",
                "type": "export_evidence",
                "phase": "export",
                "title": "Export the treasury proof",
                "description": (
                    "Expose public policy, branch transactions, exact negative outcomes, assertions, "
                    "and deterministic artifacts."
                ),
                "depends_on": ["verify_results"],
                "output_bundle_ref": "proof.bundle",
            },
            {
                "step_id": "cleanup",
                "type": "cleanup_lab",
                "phase": "cleanup",
                "title": "Clean up all treasury wallets",
                "description": "Unload only the funding, coordinator, and participant wallets owned by this lab session.",
                "depends_on": ["export_proof"],
            },
        ],
        "assertions": [
            {
                "assertion_id": "immediate_insufficient",
                "kind": "rpc_failed_with_category",
                "after_step_id": "finalize_immediate_incomplete",
                "subject_ref": "psbt.immediate.incomplete",
                "expected_category": "psbt_incomplete",
                "description": "One operator signature cannot finalize or extract the immediate spend.",
            },
            {
                "assertion_id": "immediate_psbt_incomplete",
                "kind": "psbt_incomplete",
                "after_step_id": "finalize_immediate_incomplete",
                "subject_ref": "psbt.immediate.incomplete",
                "description": "Core reports the one-operator PSBT as incomplete.",
            },
            {
                "assertion_id": "immediate_threshold_not_met",
                "kind": "signature_threshold_not_met",
                "after_step_id": "finalize_immediate_incomplete",
                "subject_ref": "psbt.immediate.partial",
                "required_signatures": 2,
                "signature_count_ref": "signatures.immediate.partial",
                "description": "The immediate PSBT contains one signature, below threshold.",
            },
            {
                "assertion_id": "immediate_threshold_met",
                "kind": "signature_threshold_met",
                "after_step_id": "sign_immediate_two",
                "subject_ref": "psbt.immediate.threshold",
                "required_signatures": 2,
                "signature_count_ref": "signatures.immediate.threshold",
                "description": "Two operators satisfy the immediate threshold.",
            },
            {
                "assertion_id": "immediate_accepted",
                "kind": "mempool_policy_accepted",
                "after_step_id": "preflight_immediate",
                "subject_ref": "acceptance.immediate",
                "description": "Core accepts the immediate spend before broadcast.",
            },
            {
                "assertion_id": "immediate_confirmed",
                "kind": "transaction_confirmed",
                "after_step_id": "decode_immediate",
                "subject_ref": "transaction.immediate.confirmed",
                "description": "The immediate spend confirms with a matching txid.",
            },
            {
                "assertion_id": "recovery_insufficient",
                "kind": "rpc_failed_with_category",
                "after_step_id": "finalize_recovery_incomplete",
                "subject_ref": "psbt.recovery.incomplete",
                "expected_category": "psbt_incomplete",
                "description": "One recovery signature cannot finalize the spend.",
            },
            {
                "assertion_id": "recovery_psbt_incomplete",
                "kind": "psbt_incomplete",
                "after_step_id": "finalize_recovery_incomplete",
                "subject_ref": "psbt.recovery.incomplete",
                "description": "Core reports the one-recovery-signature PSBT as incomplete.",
            },
            {
                "assertion_id": "recovery_threshold_not_met",
                "kind": "signature_threshold_not_met",
                "after_step_id": "finalize_recovery_incomplete",
                "subject_ref": "psbt.recovery.partial",
                "required_signatures": 2,
                "signature_count_ref": "signatures.recovery.partial",
                "description": "The recovery PSBT contains one signature, below threshold.",
            },
            {
                "assertion_id": "recovery_threshold_met",
                "kind": "signature_threshold_met",
                "after_step_id": "sign_recovery_two",
                "subject_ref": "psbt.recovery.threshold",
                "required_signatures": 2,
                "signature_count_ref": "signatures.recovery.threshold",
                "description": "Two recovery participants satisfy the signature threshold.",
            },
            {
                "assertion_id": "premature_recovery_rejected",
                "kind": "rpc_failed_with_category",
                "after_step_id": "reject_premature_recovery",
                "subject_ref": "acceptance.recovery.premature",
                "expected_category": "mempool_policy",
                "description": "Core rejects the fully signed recovery transaction as non-BIP68-final.",
            },
            {
                "assertion_id": "recovery_timelock_immature",
                "kind": "timelock_immature",
                "after_step_id": "reject_premature_recovery",
                "subject_ref": "acceptance.recovery.premature",
                "description": "The recovery output has not reached five relative blocks.",
            },
            {
                "assertion_id": "wrong_sequence_incomplete",
                "kind": "rpc_failed_with_category",
                "after_step_id": "finalize_wrong_sequence_incomplete",
                "subject_ref": "psbt.recovery.wrong_sequence.incomplete",
                "expected_category": "psbt_incomplete",
                "description": "Core refuses to finalize sequence four for older(5), even with two signatures.",
            },
            {
                "assertion_id": "recovery_timelock_mature",
                "kind": "timelock_mature",
                "after_step_id": "advance_recovery_delay",
                "subject_ref": "height.recovery.mature",
                "description": "The recovery output reaches the configured relative age.",
            },
            {
                "assertion_id": "recovery_accepted",
                "kind": "mempool_policy_accepted",
                "after_step_id": "preflight_mature_recovery",
                "subject_ref": "acceptance.recovery.mature",
                "description": "Core accepts the unchanged mature recovery transaction.",
            },
            {
                "assertion_id": "recovery_confirmed",
                "kind": "transaction_confirmed",
                "after_step_id": "decode_recovery",
                "subject_ref": "transaction.recovery.confirmed",
                "description": "The mature recovery transaction confirms with a matching txid.",
            },
            {
                "assertion_id": "emergency_insufficient",
                "kind": "rpc_failed_with_category",
                "after_step_id": "finalize_emergency_incomplete",
                "subject_ref": "psbt.emergency.incomplete",
                "expected_category": "psbt_incomplete",
                "description": "One emergency signature cannot finalize the spend.",
            },
            {
                "assertion_id": "emergency_psbt_incomplete",
                "kind": "psbt_incomplete",
                "after_step_id": "finalize_emergency_incomplete",
                "subject_ref": "psbt.emergency.incomplete",
                "description": "Core reports the one-emergency-signature PSBT as incomplete.",
            },
            {
                "assertion_id": "emergency_threshold_not_met",
                "kind": "signature_threshold_not_met",
                "after_step_id": "finalize_emergency_incomplete",
                "subject_ref": "psbt.emergency.partial",
                "required_signatures": 2,
                "signature_count_ref": "signatures.emergency.partial",
                "description": "The emergency PSBT contains one signature, below threshold.",
            },
            {
                "assertion_id": "emergency_threshold_met",
                "kind": "signature_threshold_met",
                "after_step_id": "sign_emergency_two",
                "subject_ref": "psbt.emergency.threshold",
                "required_signatures": 2,
                "signature_count_ref": "signatures.emergency.threshold",
                "description": "Two emergency participants satisfy the signature threshold.",
            },
            {
                "assertion_id": "premature_emergency_rejected",
                "kind": "rpc_failed_with_category",
                "after_step_id": "reject_premature_emergency",
                "subject_ref": "acceptance.emergency.premature",
                "expected_category": "mempool_policy",
                "description": "Core rejects the fully signed emergency transaction as non-BIP68-final.",
            },
            {
                "assertion_id": "emergency_timelock_immature",
                "kind": "timelock_immature",
                "after_step_id": "reject_premature_emergency",
                "subject_ref": "acceptance.emergency.premature",
                "description": "The emergency output has not reached ten relative blocks.",
            },
            {
                "assertion_id": "emergency_timelock_mature",
                "kind": "timelock_mature",
                "after_step_id": "advance_emergency_delay",
                "subject_ref": "height.emergency.mature",
                "description": "The emergency output reaches the configured relative age.",
            },
            {
                "assertion_id": "emergency_accepted",
                "kind": "mempool_policy_accepted",
                "after_step_id": "preflight_mature_emergency",
                "subject_ref": "acceptance.emergency.mature",
                "description": "Core accepts the unchanged mature emergency transaction.",
            },
            {
                "assertion_id": "emergency_confirmed",
                "kind": "transaction_confirmed",
                "after_step_id": "decode_emergency",
                "subject_ref": "transaction.emergency.confirmed",
                "description": "The mature emergency transaction confirms with a matching txid.",
            },
        ],
    }
)
