from app.models.curriculum import CurriculumResponse


COURSE_ROOT = "https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master"


CURRICULUM = CurriculumResponse.model_validate(
    {
        "chapters": [
            {
                "chapter": 3,
                "title": "Understand the node, wallet, and descriptors",
                "source_url": f"{COURSE_ROOT}/03_0_Understanding_Your_Bitcoin_Setup.md",
                "learning_objective": "Inspect a local Bitcoin Core node, create an isolated regtest wallet, receive funds, and relate wallet state to descriptors and UTXOs.",
                "relevant_pages": ["/", "/wallet", "/descriptors", "/regtest"],
                "relevant_scenarios": ["transaction-lifecycle"],
                "rpc_methods": ["getblockchaininfo", "createwallet", "getnewaddress", "listunspent", "listdescriptors"],
                "prerequisites": ["A reachable Bitcoin Core node", "Regtest for mutation exercises", "Basic bitcoin-cli familiarity"],
                "guided_exercise": "Create a disposable lab wallet, mine mature regtest funds, inspect its descriptor set, and identify one spendable outpoint.",
                "independent_challenge": "Explain why the wallet balance is derived from controlled UTXOs rather than an account balance stored in the chain.",
                "verification_criteria": ["Core reports the regtest chain", "The wallet is session-owned", "A mature UTXO is visible in listunspent"],
            },
            {
                "chapter": 4,
                "title": "Construct and send transactions",
                "source_url": f"{COURSE_ROOT}/04_0_Sending_Bitcoin_Transactions.md",
                "learning_objective": "Follow inputs and outputs through raw construction, wallet signing, mempool preflight, broadcast, and confirmation.",
                "relevant_pages": ["/transactions", "/regtest", "/mempool", "/scenarios"],
                "relevant_scenarios": ["transaction-lifecycle"],
                "rpc_methods": ["createrawtransaction", "fundrawtransaction", "signrawtransactionwithwallet", "testmempoolaccept", "sendrawtransaction"],
                "prerequisites": ["Chapter 3 wallet and UTXO concepts", "A funded regtest wallet"],
                "guided_exercise": "Run the transaction lifecycle scenario and inspect the backend-recorded transition from selected UTXO to confirmed transaction.",
                "independent_challenge": "Diagnose the scenario's one-satoshi overspend using Core's structured mempool result.",
                "verification_criteria": ["Preflight is accepted before broadcast", "The txid enters the mempool", "The same txid confirms", "The overspend rejection is recorded"],
            },
            {
                "chapter": 5,
                "title": "Control unconfirmed transactions",
                "source_url": f"{COURSE_ROOT}/05_0_Controlling_Bitcoin_Transactions.md",
                "learning_objective": "Distinguish opt-in RBF replacement from CPFP package fee-bumping and inspect their mempool relationships.",
                "relevant_pages": ["/tx-control", "/mempool", "/fees", "/scenarios"],
                "relevant_scenarios": ["rbf-replacement"],
                "rpc_methods": ["getmempoolentry", "bumpfee", "createrawtransaction", "fundrawtransaction", "testmempoolaccept"],
                "prerequisites": ["Chapter 4 transaction lifecycle", "Mempool policy versus consensus"],
                "guided_exercise": "Complete the reviewed RBF scenario, compare original and replacement fees, and inspect the explicit replaces relationship.",
                "independent_challenge": "Use the CPFP construction page to create a child that spends a parent output, then explain what additional scenario evidence would be required before claiming a verified package result.",
                "verification_criteria": ["Original inputs signal replacement", "Replacement has a distinct txid and higher fee", "Core evicts the original", "CPFP claims remain limited to implemented construction and preflight"],
                "implementation_note": "RBF has a Verified Scenario. CPFP construction and lifecycle relationship rendering are implemented, but the optional CPFP Verified Scenario remains deferred.",
            },
            {
                "chapter": 6,
                "title": "Build multisignature policies",
                "source_url": f"{COURSE_ROOT}/06_0_Expanding_Bitcoin_Transactions_Multisigs.md",
                "learning_objective": "Create a native-SegWit 2-of-3 policy and observe how threshold signing differs from single-key spending.",
                "relevant_pages": ["/multisig", "/psbt", "/scenarios"],
                "relevant_scenarios": ["multisig-psbt", "community-treasury-recovery"],
                "rpc_methods": ["addmultisigaddress", "sendtoaddress", "decodepsbt", "walletprocesspsbt"],
                "prerequisites": ["Chapter 4 transaction construction", "Public keys and script locking conditions"],
                "guided_exercise": "Create the reviewed 2-of-3 policy, fund it, and compare one-signature and threshold-complete evidence.",
                "independent_challenge": "Identify which artifacts must be preserved to recover a real multisig wallet without exposing private keys.",
                "verification_criteria": ["Three public keys define the policy", "One signature is insufficient", "Two signatures satisfy the threshold", "The finalized spend confirms"],
            },
            {
                "chapter": 7,
                "title": "Coordinate signing with PSBT",
                "source_url": f"{COURSE_ROOT}/07_0_Expanding_Bitcoin_Transactions_PSBTs.md",
                "learning_objective": "Separate PSBT creation, partial signing, threshold completion, finalization, and extraction while keeping private material inside signer contexts.",
                "relevant_pages": ["/psbt", "/multisig", "/keys", "/scenarios"],
                "relevant_scenarios": ["multisig-psbt", "community-treasury-recovery"],
                "rpc_methods": ["walletcreatefundedpsbt", "decodepsbt", "walletprocesspsbt", "finalizepsbt"],
                "prerequisites": ["Chapter 6 multisig", "Transaction inputs, outputs, and fees"],
                "guided_exercise": "Inspect the unsigned, one-signature, threshold-signed, and finalized PSBT lifecycle events.",
                "independent_challenge": "Complete the 2-of-3 PSBT challenge without requesting the final hint.",
                "verification_criteria": ["Partial PSBT remains incomplete", "Threshold evidence contains the required signatures", "Core finalization produces transaction hex", "Core accepts the extracted transaction"],
            },
            {
                "chapter": 8,
                "title": "Use locktime and data outputs",
                "source_url": f"{COURSE_ROOT}/08_0_Expanding_Bitcoin_Transactions_Other.md",
                "learning_objective": "Construct nLockTime transactions and small OP_RETURN data outputs, then preflight them against local Core policy.",
                "relevant_pages": ["/timelocks", "/data-tx", "/transactions", "/script"],
                "relevant_scenarios": ["cltv-timelock"],
                "rpc_methods": ["createrawtransaction", "fundrawtransaction", "signrawtransactionwithwallet", "decoderawtransaction", "testmempoolaccept"],
                "prerequisites": ["Chapter 4 raw transactions", "Hex-encoded transaction data"],
                "guided_exercise": "Build a non-final regtest transaction and separately construct a bounded OP_RETURN output without broadcasting personal data.",
                "independent_challenge": "Explain the difference between transaction nLockTime and a CLTV condition enforced inside a spent output.",
                "verification_criteria": ["Decoded nLockTime matches the requested value", "At least one input sequence enables locktime", "OP_RETURN script is provably unspendable", "Core preflight result is shown"],
                "implementation_note": "The OP_RETURN construction lab is implemented; its optional Verified Scenario remains deferred.",
            },
            {
                "chapter": 9,
                "title": "Read and test Bitcoin Script",
                "source_url": f"{COURSE_ROOT}/09_0_Introducing_Bitcoin_Scripts.md",
                "learning_objective": "Decode locking scripts, relate stack conditions to transaction outputs, and test complete spends through Bitcoin Core.",
                "relevant_pages": ["/script", "/script-lab", "/transactions"],
                "relevant_scenarios": ["transaction-lifecycle"],
                "rpc_methods": ["decodescript", "decoderawtransaction", "testmempoolaccept"],
                "prerequisites": ["Chapter 4 transaction structure", "Basic stack notation"],
                "guided_exercise": "Decode a standard output script, find it in a transaction, and inspect the safe Core preflight result for a complete spend.",
                "independent_challenge": "Diagnose a rejected transaction by separating serialization, missing-input, script, and value-conservation failures.",
                "verification_criteria": ["Script hex decodes through Core", "The locking condition is identified", "A full transaction is used for preflight", "The Core rejection reason is preserved"],
            },
            {
                "chapter": 10,
                "title": "Wrap policies with P2SH and P2WSH",
                "source_url": f"{COURSE_ROOT}/10_0_Embedding_Bitcoin_Scripts_in_P2SH_Transactions.md",
                "learning_objective": "Compare redeem-script and witness-script commitments and trace a policy from public script to spend witness.",
                "relevant_pages": ["/script-lab", "/multisig", "/transactions", "/scenarios"],
                "relevant_scenarios": ["multisig-psbt", "cltv-timelock", "community-treasury-recovery"],
                "rpc_methods": ["decodescript", "addmultisigaddress", "getdescriptorinfo", "decoderawtransaction"],
                "prerequisites": ["Chapter 9 Script", "Hash commitments", "SegWit transaction structure"],
                "guided_exercise": "Compare the multisig and CLTV P2WSH evidence, including witness script and final witness stack.",
                "independent_challenge": "Explain what Core can verify from the final transaction and which policy metadata must be retained separately.",
                "verification_criteria": ["Script commitment matches its wrapper", "Funding output uses the expected script type", "Final witness satisfies the committed script"],
            },
            {
                "chapter": 11,
                "title": "Enforce CLTV and CSV timelocks",
                "source_url": f"{COURSE_ROOT}/11_0_Empowering_Timelock_with_Bitcoin_Scripts.md",
                "learning_objective": "Distinguish absolute CLTV from relative CSV and prove both premature rejection and mature acceptance.",
                "relevant_pages": ["/timelocks", "/script-lab", "/scenarios"],
                "relevant_scenarios": ["cltv-timelock", "community-treasury-recovery"],
                "rpc_methods": ["getblockcount", "createrawtransaction", "testmempoolaccept", "generatetoaddress"],
                "prerequisites": ["Chapter 8 nLockTime", "Chapter 10 P2WSH", "Sequence semantics"],
                "guided_exercise": "Run the CLTV scenario, then compare its absolute maturity event with the treasury recovery branch's relative-delay maturity.",
                "independent_challenge": "Demonstrate the premature CLTV failure and identify the exact unchanged transaction later accepted at maturity.",
                "verification_criteria": ["Premature spend is rejected for the reviewed reason", "Locktime and sequence are preserved", "Maturity height is recorded", "The unchanged mature spend confirms"],
            },
            {
                "chapter": 12,
                "title": "Compose conditions and advanced operations",
                "source_url": f"{COURSE_ROOT}/12_0_Expanding_Bitcoin_Scripts.md",
                "learning_objective": "Build conditional branches and hash or signature checks while keeping policy claims tied to scripts Core actually validates.",
                "relevant_pages": ["/script-lab", "/script", "/scenarios"],
                "relevant_scenarios": ["community-treasury-recovery"],
                "rpc_methods": ["decodescript", "getdescriptorinfo", "deriveaddresses", "testmempoolaccept"],
                "prerequisites": ["Chapters 9-11", "Boolean and stack reasoning"],
                "guided_exercise": "Generate conditional templates in Script Lab and inspect the treasury policy's three public branches and satisfaction paths.",
                "independent_challenge": "Trace which selector, signatures, and sequence value satisfy each treasury branch without using private key exports.",
                "verification_criteria": ["Every claimed branch exists in the public policy", "Branch requirements match observed witness data", "Core validates each completed spend"],
            },
            {
                "chapter": 13,
                "title": "Design and prove a real policy",
                "source_url": f"{COURSE_ROOT}/13_0_Designing_Real_Bitcoin_Scripts.md",
                "learning_objective": "Turn operational requirements into a reviewable spending policy and prove each supported branch, negative boundary, and cleanup result.",
                "relevant_pages": ["/scenarios", "/script-lab", "/multisig", "/psbt", "/timelocks"],
                "relevant_scenarios": ["community-treasury-recovery"],
                "rpc_methods": ["getdescriptorinfo", "importdescriptors", "createpsbt", "walletprocesspsbt", "finalizepsbt", "testmempoolaccept"],
                "prerequisites": ["Chapters 3-12", "Threat modeling", "Key and backup boundaries"],
                "guided_exercise": "Run Community Treasury Recovery and review the operator, recovery, and emergency tracks plus the Proof of Spendability export.",
                "independent_challenge": "Complete the treasury recovery challenge and defend which claims the regtest evidence proves and which production claims remain out of scope.",
                "verification_criteria": ["All three branches match the public descriptor", "Threshold and premature failures are classified", "Mature recovery and emergency spends confirm", "Cleanup and deterministic proof export succeed"],
            },
        ],
        "explanation": "This mapping summarizes Chapters 3-13 and links to the original course. It includes only BitScope pages and Verified Scenarios present in this repository, with explicit notes where an optional scenario is still deferred.",
    }
)


class CurriculumService:
    def curriculum(self) -> CurriculumResponse:
        return CURRICULUM.model_copy(deep=True)
