from app.models.scenario import ScenarioDefinition


MULTISIG_PSBT_SCENARIO = ScenarioDefinition.model_validate(
    {
        "scenario_id": "multisig-psbt",
        "version": "1.0.0",
        "name": "Multisig PSBT threshold",
        "summary": (
            "Create a 2-of-3 multisig policy across three session-owned legacy signer wallets, prove that one "
            "signature cannot finalize the PSBT, add the second signature, then preflight, broadcast, and confirm the spend."
        ),
        "difficulty": "intermediate",
        "related_lbcli_chapters": [6, 7],
        "concepts": [
            "2-of-3 multisig",
            "PSBT",
            "Signature threshold",
            "Finalization",
            "Legacy wallet compatibility",
        ],
        "required_capabilities": ["read_only", "wallet_read", "regtest_mutation"],
        "estimated_run_steps": 22,
        "steps": [
            {
                "step_id": "verify_chain",
                "type": "verify_runtime_chain",
                "phase": "setup",
                "title": "Verify the runtime chain",
                "description": "Require the configured node and live Bitcoin Core chain to agree on regtest.",
                "output_context_ref": "node.context",
            },
            {
                "step_id": "prepare_funding_wallet",
                "type": "prepare_isolated_wallet",
                "phase": "setup",
                "title": "Prepare the funding wallet",
                "description": "Use only the active wallet owned by this run's lab session for funding and mining.",
                "depends_on": ["verify_chain"],
                "wallet_role": "funder",
                "output_wallet_ref": "wallet.funder",
            },
            {
                "step_id": "prepare_signer_wallets",
                "type": "prepare_multisig_signers",
                "phase": "setup",
                "title": "Prepare three signer wallets",
                "description": "Create three session-owned legacy wallets with one signer key context each.",
                "depends_on": ["prepare_funding_wallet"],
                "signer_count": 3,
                "legacy_wallets": True,
                "output_wallets_ref": "wallets.signers",
            },
            {
                "step_id": "generate_mining_address",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate a mining address",
                "description": "Generate a fresh funding-wallet address for maturity and confirmation blocks.",
                "depends_on": ["prepare_signer_wallets"],
                "wallet_ref": "wallet.funder",
                "label": "bitscope-multisig-mining",
                "address_type": "bech32",
                "output_address_ref": "address.mining",
            },
            {
                "step_id": "mine_mature_funds",
                "type": "mine_blocks",
                "phase": "setup",
                "title": "Mine mature funding",
                "description": "Mine 101 blocks in bounded batches so the funding wallet can spend.",
                "depends_on": ["generate_mining_address"],
                "address_ref": "address.mining",
                "blocks": 101,
                "output_blocks_ref": "blocks.maturity",
            },
            {
                "step_id": "create_multisig",
                "type": "create_multisig_address",
                "phase": "setup",
                "title": "Create the 2-of-3 policy",
                "description": "Collect one public key from each signer wallet and register the same native SegWit script.",
                "depends_on": ["mine_mature_funds"],
                "signer_wallets_ref": "wallets.signers",
                "required_signatures": 2,
                "address_type": "bech32",
                "output_multisig_ref": "multisig.policy",
            },
            {
                "step_id": "fund_multisig",
                "type": "fund_multisig",
                "phase": "setup",
                "title": "Fund the multisig output",
                "description": "Send 0.5 BTC to the fresh multisig address with an explicit 2 sat/vB fee rate.",
                "depends_on": ["create_multisig"],
                "wallet_ref": "wallet.funder",
                "multisig_ref": "multisig.policy",
                "amount_btc": "0.50000000",
                "fee_rate_sat_vb": "2.000",
                "output_txid_ref": "funding.txid",
            },
            {
                "step_id": "confirm_multisig_funding",
                "type": "mine_confirmation_blocks",
                "phase": "setup",
                "title": "Confirm the funding output",
                "description": "Mine one block so every registered signer wallet can select the multisig UTXO.",
                "depends_on": ["fund_multisig"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.funding_confirmation",
            },
            {
                "step_id": "generate_destination",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate the spend destination",
                "description": "Generate a fresh funding-wallet destination for the multisig spend.",
                "depends_on": ["confirm_multisig_funding"],
                "wallet_ref": "wallet.funder",
                "label": "bitscope-multisig-destination",
                "address_type": "bech32",
                "output_address_ref": "address.destination",
            },
            {
                "step_id": "create_spend_psbt",
                "type": "create_multisig_psbt",
                "phase": "execution",
                "title": "Create the unsigned spend PSBT",
                "description": "Spend the confirmed multisig UTXO to the destination without signing it.",
                "depends_on": ["generate_destination"],
                "signer_wallets_ref": "wallets.signers",
                "multisig_ref": "multisig.policy",
                "recipient_address_ref": "address.destination",
                "amount_btc": "0.25000000",
                "fee_rate_sat_vb": "2.000",
                "output_psbt_ref": "psbt.unsigned",
            },
            {
                "step_id": "sign_with_one",
                "type": "process_psbt",
                "phase": "execution",
                "title": "Add one signature",
                "description": "Process the PSBT with only the first signer wallet.",
                "depends_on": ["create_spend_psbt"],
                "wallet_ref": "wallets.signers",
                "psbt_ref": "psbt.unsigned",
                "sign": True,
                "finalize": False,
                "output_psbt_ref": "psbt.partial",
                "output_signature_count_ref": "signatures.partial_count",
            },
            {
                "step_id": "verify_incomplete",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Prove insufficient signatures",
                "description": "Require finalization with one signature to remain incomplete and unextractable.",
                "depends_on": ["sign_with_one"],
                "psbt_ref": "psbt.partial",
                "extract": False,
                "output_psbt_ref": "psbt.partial_finalized",
            },
            {
                "step_id": "sign_with_second",
                "type": "process_psbt",
                "phase": "attack",
                "title": "Reach the signature threshold",
                "description": "Process the partial PSBT with the second signer wallet.",
                "depends_on": ["verify_incomplete"],
                "wallet_ref": "wallets.signers",
                "psbt_ref": "psbt.partial",
                "sign": True,
                "finalize": False,
                "output_psbt_ref": "psbt.threshold",
                "output_signature_count_ref": "signatures.threshold_count",
            },
            {
                "step_id": "finalize_psbt",
                "type": "finalize_psbt",
                "phase": "attack",
                "title": "Finalize and extract",
                "description": "Finalize the threshold-complete PSBT and extract raw transaction hex.",
                "depends_on": ["sign_with_second"],
                "psbt_ref": "psbt.threshold",
                "extract": True,
                "output_transaction_ref": "transaction.signed",
            },
            {
                "step_id": "preflight_spend",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Preflight the multisig spend",
                "description": "Require Bitcoin Core to accept the finalized transaction before broadcast.",
                "depends_on": ["finalize_psbt"],
                "transaction_ref": "transaction.signed",
                "output_acceptance_ref": "acceptance.spend",
            },
            {
                "step_id": "broadcast_spend",
                "type": "broadcast_transaction",
                "phase": "attack",
                "title": "Broadcast the multisig spend",
                "description": "Broadcast only the preflighted, threshold-complete transaction.",
                "depends_on": ["preflight_spend"],
                "transaction_ref": "transaction.signed",
                "output_txid_ref": "spend.txid",
            },
            {
                "step_id": "inspect_spend_mempool",
                "type": "query_mempool_entry",
                "phase": "attack",
                "title": "Inspect the spend in mempool",
                "description": "Record the broadcast multisig spend's mempool entry.",
                "depends_on": ["broadcast_spend"],
                "txid_ref": "spend.txid",
                "output_mempool_ref": "spend.mempool",
            },
            {
                "step_id": "confirm_spend",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm the multisig spend",
                "description": "Mine one block containing the multisig spend.",
                "depends_on": ["inspect_spend_mempool"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.spend_confirmation",
            },
            {
                "step_id": "decode_confirmed_spend",
                "type": "decode_transaction",
                "phase": "attack",
                "title": "Decode the confirmed spend",
                "description": "Read and decode the confirmed multisig transaction.",
                "depends_on": ["confirm_spend"],
                "transaction_ref": "transaction.signed",
                "output_decoded_ref": "spend.confirmed",
            },
            {
                "step_id": "verify_results",
                "type": "evaluate_assertions",
                "phase": "verification",
                "title": "Evaluate multisig assertions",
                "description": "Evaluate incomplete and threshold-complete PSBT states plus transaction acceptance.",
                "depends_on": ["decode_confirmed_spend"],
                "assertion_ids": [
                    "insufficient_signatures",
                    "partial_psbt_incomplete",
                    "threshold_not_met",
                    "threshold_met",
                    "psbt_complete",
                    "spend_accepted",
                    "spend_confirmed",
                ],
            },
            {
                "step_id": "export_proof",
                "type": "export_evidence",
                "phase": "export",
                "title": "Export the proof bundle",
                "description": "Expose PSBT stages, assertions, Core output, commands, manifest, and ZIP export.",
                "depends_on": ["verify_results"],
                "output_bundle_ref": "proof.bundle",
            },
            {
                "step_id": "cleanup",
                "type": "cleanup_lab",
                "phase": "cleanup",
                "title": "Clean up all session wallets",
                "description": "Unload only the funding and signer wallets recorded as owned by this lab session.",
                "depends_on": ["export_proof"],
            },
        ],
        "assertions": [
            {
                "assertion_id": "insufficient_signatures",
                "kind": "rpc_failed_with_category",
                "after_step_id": "verify_incomplete",
                "subject_ref": "psbt.partial_finalized",
                "expected_category": "psbt_incomplete",
                "description": "One signature cannot finalize or extract the 2-of-3 spend.",
            },
            {
                "assertion_id": "partial_psbt_incomplete",
                "kind": "psbt_incomplete",
                "after_step_id": "verify_incomplete",
                "subject_ref": "psbt.partial_finalized",
                "description": "Bitcoin Core reports the one-signature PSBT as incomplete.",
            },
            {
                "assertion_id": "threshold_not_met",
                "kind": "signature_threshold_not_met",
                "after_step_id": "verify_incomplete",
                "subject_ref": "psbt.partial",
                "required_signatures": 2,
                "signature_count_ref": "signatures.partial_count",
                "description": "The partial PSBT contains one signature, below the required threshold of two.",
            },
            {
                "assertion_id": "threshold_met",
                "kind": "signature_threshold_met",
                "after_step_id": "sign_with_second",
                "subject_ref": "psbt.threshold",
                "required_signatures": 2,
                "signature_count_ref": "signatures.threshold_count",
                "description": "The second signer raises the PSBT to the required threshold.",
            },
            {
                "assertion_id": "psbt_complete",
                "kind": "psbt_complete",
                "after_step_id": "finalize_psbt",
                "subject_ref": "transaction.signed",
                "description": "Bitcoin Core finalized and extracted the threshold-complete PSBT.",
            },
            {
                "assertion_id": "spend_accepted",
                "kind": "mempool_policy_accepted",
                "after_step_id": "preflight_spend",
                "subject_ref": "acceptance.spend",
                "description": "Bitcoin Core accepted the finalized multisig spend during preflight.",
            },
            {
                "assertion_id": "spend_confirmed",
                "kind": "transaction_confirmed",
                "after_step_id": "decode_confirmed_spend",
                "subject_ref": "spend.confirmed",
                "description": "The multisig spend has at least one confirmation and a matching decoded txid.",
            },
        ],
    }
)
