from app.models.scenario import ScenarioDefinition


RBF_REPLACEMENT_SCENARIO = ScenarioDefinition.model_validate(
    {
        "scenario_id": "rbf-replacement",
        "version": "1.0.0",
        "name": "RBF replacement",
        "summary": (
            "Create an explicitly replaceable regtest transaction, record its sequence and mempool policy, "
            "prove that Bitcoin Core rejects a same-rate bump, then broadcast and confirm a higher-fee replacement."
        ),
        "difficulty": "intermediate",
        "related_lbcli_chapters": [5, 7],
        "concepts": [
            "Replace-by-fee",
            "BIP125 signaling",
            "Incremental relay fee",
            "Mempool replacement",
            "Confirmation",
        ],
        "required_capabilities": ["read_only", "wallet_read", "regtest_mutation"],
        "estimated_run_steps": 17,
        "steps": [
            {
                "step_id": "verify_chain",
                "type": "verify_runtime_chain",
                "phase": "setup",
                "title": "Verify the runtime chain",
                "description": "Require the configured node and live Bitcoin Core chain to agree on regtest.",
                "output_context_ref": "node.context",
            },
            {
                "step_id": "prepare_wallet",
                "type": "prepare_isolated_wallet",
                "phase": "setup",
                "title": "Prepare the isolated wallet",
                "description": "Verify and use only the wallet owned by this run's active lab session.",
                "depends_on": ["verify_chain"],
                "wallet_role": "operator",
                "output_wallet_ref": "wallet.operator",
            },
            {
                "step_id": "generate_mining_address",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate a mining address",
                "description": "Generate a fresh bech32 address in the session-owned wallet.",
                "depends_on": ["prepare_wallet"],
                "wallet_ref": "wallet.operator",
                "label": "bitscope-rbf-mining",
                "address_type": "bech32",
                "output_address_ref": "address.mining",
            },
            {
                "step_id": "mine_mature_funds",
                "type": "mine_blocks",
                "phase": "setup",
                "title": "Mine mature funds",
                "description": "Mine 101 blocks in bounded batches so the wallet can fund the original transaction.",
                "depends_on": ["generate_mining_address"],
                "address_ref": "address.mining",
                "blocks": 101,
                "output_blocks_ref": "blocks.maturity",
            },
            {
                "step_id": "generate_recipient",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate the recipient",
                "description": "Generate a fresh destination for the replaceable wallet transaction.",
                "depends_on": ["mine_mature_funds"],
                "wallet_ref": "wallet.operator",
                "label": "bitscope-rbf-recipient",
                "address_type": "bech32",
                "output_address_ref": "address.recipient",
            },
            {
                "step_id": "create_original",
                "type": "create_wallet_rbf_transaction",
                "phase": "execution",
                "title": "Create the opt-in RBF transaction",
                "description": "Broadcast a 0.1 BTC wallet transaction with replaceable=true and a 2 sat/vB fee rate.",
                "depends_on": ["generate_recipient"],
                "wallet_ref": "wallet.operator",
                "recipient_address_ref": "address.recipient",
                "amount_btc": "0.10000000",
                "initial_fee_rate_sat_vb": "2.000",
                "output_transaction_ref": "original.transaction",
                "output_txid_ref": "original.txid",
            },
            {
                "step_id": "decode_original",
                "type": "decode_transaction",
                "phase": "execution",
                "title": "Record sequence signaling",
                "description": "Decode the original transaction and retain every input sequence value.",
                "depends_on": ["create_original"],
                "transaction_ref": "original.transaction",
                "output_decoded_ref": "original.decoded",
            },
            {
                "step_id": "inspect_original_mempool",
                "type": "query_mempool_entry",
                "phase": "execution",
                "title": "Inspect the original mempool entry",
                "description": "Require Bitcoin Core to report the original as BIP125 replaceable.",
                "depends_on": ["decode_original"],
                "txid_ref": "original.txid",
                "output_mempool_ref": "original.mempool",
            },
            {
                "step_id": "reject_insufficient_bump",
                "type": "bump_fee",
                "phase": "attack",
                "title": "Attempt an insufficient fee bump",
                "description": "Request the original observed fee rate and require Core's incremental-fee rejection.",
                "depends_on": ["inspect_original_mempool"],
                "wallet_ref": "wallet.operator",
                "txid_ref": "original.txid",
                "fee_rate_sat_vb": "2.000",
                "output_replacement_ref": "attack.insufficient_bump",
            },
            {
                "step_id": "replace_transaction",
                "type": "bump_fee",
                "phase": "attack",
                "title": "Broadcast a higher-fee replacement",
                "description": "Add 10 sat/vB to the observed original fee rate and require a new transaction id.",
                "depends_on": ["reject_insufficient_bump"],
                "wallet_ref": "wallet.operator",
                "txid_ref": "original.txid",
                "add_to_observed_fee_rate_sat_vb": "10.000",
                "output_replacement_ref": "replacement.transaction",
                "output_txid_ref": "replacement.txid",
            },
            {
                "step_id": "verify_original_evicted",
                "type": "query_mempool_entry",
                "phase": "attack",
                "title": "Verify original eviction",
                "description": "Require the original transaction to be absent from the mempool after replacement.",
                "depends_on": ["replace_transaction"],
                "txid_ref": "original.txid",
                "output_mempool_ref": "original.evicted",
            },
            {
                "step_id": "inspect_replacement_mempool",
                "type": "query_mempool_entry",
                "phase": "attack",
                "title": "Inspect the replacement mempool entry",
                "description": "Record the replacement's live fee and mempool metadata.",
                "depends_on": ["verify_original_evicted"],
                "txid_ref": "replacement.txid",
                "output_mempool_ref": "replacement.mempool",
            },
            {
                "step_id": "confirm_replacement",
                "type": "mine_confirmation_blocks",
                "phase": "attack",
                "title": "Confirm the replacement",
                "description": "Mine one block containing the higher-fee replacement.",
                "depends_on": ["inspect_replacement_mempool"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.confirmation",
            },
            {
                "step_id": "decode_confirmed_replacement",
                "type": "decode_transaction",
                "phase": "attack",
                "title": "Decode the confirmed replacement",
                "description": "Read the replacement from the wallet and decode its confirmed serialization.",
                "depends_on": ["confirm_replacement"],
                "transaction_ref": "replacement.transaction",
                "output_decoded_ref": "replacement.confirmed",
            },
            {
                "step_id": "verify_results",
                "type": "evaluate_assertions",
                "phase": "verification",
                "title": "Evaluate RBF assertions",
                "description": "Evaluate signaling, insufficient-fee rejection, replacement, and confirmation.",
                "depends_on": ["decode_confirmed_replacement"],
                "assertion_ids": [
                    "original_signaled_rbf",
                    "insufficient_bump_rejected",
                    "original_replaced",
                    "replacement_in_mempool",
                    "replacement_confirmed",
                ],
            },
            {
                "step_id": "export_proof",
                "type": "export_evidence",
                "phase": "export",
                "title": "Export the proof bundle",
                "description": "Expose deterministic evidence, assertions, commands, manifest, and ZIP export.",
                "depends_on": ["verify_results"],
                "output_bundle_ref": "proof.bundle",
            },
            {
                "step_id": "cleanup",
                "type": "cleanup_lab",
                "phase": "cleanup",
                "title": "Clean up the isolated wallet",
                "description": "Unload only wallets recorded as owned by this lab session.",
                "depends_on": ["export_proof"],
            },
        ],
        "assertions": [
            {
                "assertion_id": "original_signaled_rbf",
                "kind": "rbf_signaled",
                "after_step_id": "inspect_original_mempool",
                "subject_ref": "original.decoded",
                "description": "At least one input sequence signals opt-in RBF and Core reports BIP125 replaceability.",
            },
            {
                "assertion_id": "insufficient_bump_rejected",
                "kind": "rpc_failed_with_category",
                "after_step_id": "reject_insufficient_bump",
                "subject_ref": "attack.insufficient_bump",
                "expected_category": "mempool_policy",
                "description": "Core rejected a same-rate bump because it did not pay the incremental replacement fee.",
            },
            {
                "assertion_id": "original_replaced",
                "kind": "transaction_replaced",
                "after_step_id": "verify_original_evicted",
                "subject_ref": "original.evicted",
                "description": "The original txid is absent from the mempool after the higher-fee replacement.",
            },
            {
                "assertion_id": "replacement_in_mempool",
                "kind": "transaction_in_mempool",
                "after_step_id": "inspect_replacement_mempool",
                "subject_ref": "replacement.mempool",
                "description": "Bitcoin Core returned a mempool entry for the replacement txid.",
            },
            {
                "assertion_id": "replacement_confirmed",
                "kind": "transaction_confirmed",
                "after_step_id": "decode_confirmed_replacement",
                "subject_ref": "replacement.confirmed",
                "description": "The replacement has at least one confirmation and a matching decoded txid.",
            },
        ],
    }
)
