from app.models.scenario import ScenarioDefinition


TRANSACTION_LIFECYCLE_SCENARIO = ScenarioDefinition.model_validate(
    {
        "scenario_id": "transaction-lifecycle",
        "version": "1.0.0",
        "name": "Transaction lifecycle",
        "summary": (
            "Follow two freshly matured regtest UTXOs through explicit selection, raw transaction "
            "construction, wallet signing, mempool preflight, broadcast, mempool observation, confirmation, "
            "and final decoding; then prove that Bitcoin Core rejects a signed overspend transaction."
        ),
        "difficulty": "beginner",
        "related_lbcli_chapters": [3, 4, 5, 7],
        "concepts": [
            "Transaction lifecycle",
            "UTXO selection",
            "Wallet signing",
            "Mempool policy",
            "Confirmation",
            "Consensus rejection",
        ],
        "required_capabilities": ["read_only", "wallet_read", "regtest_mutation"],
        "estimated_run_steps": 19,
        "steps": [
            {
                "step_id": "verify_chain",
                "type": "verify_runtime_chain",
                "phase": "setup",
                "title": "Verify the runtime chain",
                "description": "Require the configured node and live Bitcoin Core chain to agree on regtest.",
                "output_context_ref": "node.context",
            },
            {
                "step_id": "prepare_wallet",
                "type": "prepare_isolated_wallet",
                "phase": "setup",
                "title": "Prepare the isolated wallet",
                "description": "Verify and use only the wallet owned by this run's active lab session.",
                "depends_on": ["verify_chain"],
                "wallet_role": "operator",
                "output_wallet_ref": "wallet.operator",
            },
            {
                "step_id": "generate_mining_address",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate a mining address",
                "description": "Generate a fresh bech32 address in the session-owned wallet.",
                "depends_on": ["prepare_wallet"],
                "wallet_ref": "wallet.operator",
                "label": "bitscope-lifecycle-mining",
                "address_type": "bech32",
                "output_address_ref": "address.mining",
            },
            {
                "step_id": "mine_mature_funds",
                "type": "mine_blocks",
                "phase": "setup",
                "title": "Mine mature funds",
                "description": "Mine 102 blocks so two new coinbase outputs reach 101 confirmations.",
                "depends_on": ["generate_mining_address"],
                "address_ref": "address.mining",
                "blocks": 102,
                "output_blocks_ref": "blocks.maturity",
            },
            {
                "step_id": "generate_recipient",
                "type": "generate_address",
                "phase": "setup",
                "title": "Generate the recipient",
                "description": "Generate a distinct fresh destination address for this run.",
                "depends_on": ["mine_mature_funds"],
                "wallet_ref": "wallet.operator",
                "label": "bitscope-lifecycle-recipient",
                "address_type": "bech32",
                "output_address_ref": "address.recipient",
            },
            {
                "step_id": "select_utxos",
                "type": "select_utxos",
                "phase": "execution",
                "title": "Select two mature UTXOs",
                "description": "Select two distinct spendable coinbase outputs with at least 101 confirmations.",
                "depends_on": ["generate_recipient"],
                "wallet_ref": "wallet.operator",
                "minimum_amount_btc": "0.00001000",
                "minimum_confirmations": 101,
                "output_utxos_ref": "utxos.selected",
            },
            {
                "step_id": "construct_transaction",
                "type": "create_selected_utxo_transaction",
                "phase": "execution",
                "title": "Construct the transaction",
                "description": "Spend the first selected UTXO and leave an explicit 10,000 satoshi fee.",
                "depends_on": ["select_utxos"],
                "utxos_ref": "utxos.selected",
                "selected_index": 0,
                "recipient_address_ref": "address.recipient",
                "fee_sats": 10000,
                "output_transaction_ref": "transaction.unsigned",
            },
            {
                "step_id": "sign_transaction",
                "type": "sign_raw_transaction",
                "phase": "execution",
                "title": "Sign the transaction",
                "description": "Ask the isolated wallet to sign the selected input completely.",
                "depends_on": ["construct_transaction"],
                "wallet_ref": "wallet.operator",
                "transaction_ref": "transaction.unsigned",
                "output_transaction_ref": "transaction.signed",
            },
            {
                "step_id": "preflight_transaction",
                "type": "test_mempool_accept",
                "phase": "execution",
                "title": "Preflight mempool acceptance",
                "description": "Use Bitcoin Core's structured testmempoolaccept result before broadcast.",
                "depends_on": ["sign_transaction"],
                "transaction_ref": "transaction.signed",
                "output_acceptance_ref": "acceptance.normal",
            },
            {
                "step_id": "broadcast_transaction",
                "type": "broadcast_transaction",
                "phase": "execution",
                "title": "Broadcast the transaction",
                "description": "Broadcast only after the positive preflight succeeds.",
                "depends_on": ["preflight_transaction"],
                "transaction_ref": "transaction.signed",
                "output_txid_ref": "transaction.txid",
            },
            {
                "step_id": "inspect_mempool",
                "type": "query_mempool_entry",
                "phase": "execution",
                "title": "Inspect the mempool entry",
                "description": "Record Bitcoin Core's live mempool metadata for the broadcast transaction.",
                "depends_on": ["broadcast_transaction"],
                "txid_ref": "transaction.txid",
                "output_mempool_ref": "mempool.entry",
            },
            {
                "step_id": "confirm_transaction",
                "type": "mine_confirmation_blocks",
                "phase": "execution",
                "title": "Confirm the transaction",
                "description": "Mine one block to confirm the transaction on regtest.",
                "depends_on": ["inspect_mempool"],
                "address_ref": "address.mining",
                "blocks": 1,
                "output_blocks_ref": "blocks.confirmation",
            },
            {
                "step_id": "decode_confirmed_transaction",
                "type": "decode_transaction",
                "phase": "execution",
                "title": "Decode the confirmed transaction",
                "description": "Read the wallet transaction and decode its final confirmed serialization.",
                "depends_on": ["confirm_transaction"],
                "transaction_ref": "transaction.signed",
                "output_decoded_ref": "transaction.confirmed",
            },
            {
                "step_id": "construct_overspend",
                "type": "create_overspend_transaction",
                "phase": "attack",
                "title": "Construct an overspend transaction",
                "description": "Create a valid serialization whose output exceeds the second selected input by one satoshi.",
                "depends_on": ["decode_confirmed_transaction"],
                "utxos_ref": "utxos.selected",
                "selected_index": 1,
                "recipient_address_ref": "address.recipient",
                "excess_sats": 1,
                "output_transaction_ref": "attack.unsigned",
            },
            {
                "step_id": "sign_overspend",
                "type": "sign_raw_transaction",
                "phase": "attack",
                "title": "Sign the overspend transaction",
                "description": "Prove that wallet signing can complete even though the transaction violates value conservation.",
                "depends_on": ["construct_overspend"],
                "wallet_ref": "wallet.operator",
                "transaction_ref": "attack.unsigned",
                "output_transaction_ref": "attack.signed",
            },
            {
                "step_id": "reject_overspend",
                "type": "test_mempool_accept",
                "phase": "attack",
                "title": "Prove overspend rejection",
                "description": "Require Bitcoin Core to reject the signed transaction with a structured consensus reason.",
                "depends_on": ["sign_overspend"],
                "transaction_ref": "attack.signed",
                "output_acceptance_ref": "acceptance.overspend",
            },
            {
                "step_id": "verify_results",
                "type": "evaluate_assertions",
                "phase": "verification",
                "title": "Evaluate lifecycle assertions",
                "description": "Evaluate the positive lifecycle and expected negative-path results.",
                "depends_on": ["reject_overspend"],
                "assertion_ids": [
                    "preflight_accepted",
                    "observed_in_mempool",
                    "transaction_confirmed",
                    "overspend_rejected",
                ],
            },
            {
                "step_id": "export_proof",
                "type": "export_evidence",
                "phase": "export",
                "title": "Export the proof bundle",
                "description": "Expose deterministic evidence, report, transcript, commands, manifest, and ZIP export.",
                "depends_on": ["verify_results"],
                "output_bundle_ref": "proof.bundle",
            },
            {
                "step_id": "cleanup",
                "type": "cleanup_lab",
                "phase": "cleanup",
                "title": "Clean up the isolated wallet",
                "description": "Unload only wallets recorded as owned by this lab session.",
                "depends_on": ["export_proof"],
            },
        ],
        "assertions": [
            {
                "assertion_id": "preflight_accepted",
                "kind": "mempool_policy_accepted",
                "after_step_id": "preflight_transaction",
                "subject_ref": "acceptance.normal",
                "description": "Bitcoin Core accepted the signed transaction during preflight.",
            },
            {
                "assertion_id": "observed_in_mempool",
                "kind": "transaction_in_mempool",
                "after_step_id": "inspect_mempool",
                "subject_ref": "mempool.entry",
                "description": "The broadcast transaction was observed in Bitcoin Core's mempool.",
            },
            {
                "assertion_id": "transaction_confirmed",
                "kind": "transaction_confirmed",
                "after_step_id": "decode_confirmed_transaction",
                "subject_ref": "transaction.confirmed",
                "description": "The transaction has at least one confirmation and its final serialization decodes.",
            },
            {
                "assertion_id": "overspend_rejected",
                "kind": "rpc_failed_with_category",
                "after_step_id": "reject_overspend",
                "subject_ref": "acceptance.overspend",
                "expected_category": "consensus_validation",
                "description": "Bitcoin Core rejected the signed overspend transaction for value-conservation failure.",
            },
        ],
    }
)
